# This workflow will publish a Python package to PyPI when a release is created.
# For more information, see: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    # This job needs an OIDC token to authenticate with PyPI.
    # See https://docs.pypi.org/trusted-publishers/
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Files in .github/workflows:"
          ls -la .github/workflows/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build package
        run: |
          echo "Building package from: $(pwd)"
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 